<div class="page-title container-fluid">
  <h1 class="extended uppercase s-medium">
    <?php if (is_archive()): ?>
      <?php echo get_the_archive_title( '', false ); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo get_the_archive_title( '', false ); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo get_the_archive_title( '', false ); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo get_the_archive_title( '', false ); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo get_the_archive_title( '', false ); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo get_the_archive_title( '', false ); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo get_the_archive_title( '', false ); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo get_the_archive_title( '', false ); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo get_the_archive_title( '', false ); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo get_the_archive_title( '', false ); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo get_the_archive_title( '', false ); ?>&nbsp;&nbsp;&nbsp;&nbsp;

    <?php elseif (is_search()): ?>
      <?php echo $total_results; _e (" risultati per '",'sa_theme'); the_search_query(); _e ("'",'sa_theme');?>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $total_results; _e (" risultati per '",'sa_theme'); the_search_query(); _e ("'",'sa_theme');?>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $total_results; _e (" risultati per '",'sa_theme'); the_search_query(); _e ("'",'sa_theme');?>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $total_results; _e (" risultati per '",'sa_theme'); the_search_query(); _e ("'",'sa_theme');?>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $total_results; _e (" risultati per '",'sa_theme'); the_search_query(); _e ("'",'sa_theme');?>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $total_results; _e (" risultati per '",'sa_theme'); the_search_query(); _e ("'",'sa_theme');?>&nbsp;&nbsp;&nbsp;&nbsp;
    <?php else: ?>
      <?php the_title(); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php the_title(); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php the_title(); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php the_title(); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php the_title(); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php the_title(); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php the_title(); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php the_title(); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php the_title(); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php the_title(); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php the_title(); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php the_title(); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php the_title(); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php the_title(); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php the_title(); ?>&nbsp;&nbsp;&nbsp;&nbsp;
    <?php endif; ?>
  </h1>
</div>